version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: America/Cancun
  open-pull-requests-limit: 99
  reviewers:
  - bbarker
  ignore:
  - dependency-name: purescript
    versions:
    - 0.14.0
